# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: APROSMIG — ASSOCIAÇÃO DAS PROSTITUTAS DE MINAS GERAIS
email: aprosmig@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A APROSMIG -  Associação das Prostitutas de Minas Gerais, criada em 2009, é
  uma agente de direitos ao trabalho, promoção da cidadania e de combate à
  violência de gênero e ao tráfico de pessoas, com uma importante atuação como
  agente de saúde e segurança públicas, além de agente cultural. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
#github_username:  jekyll
phone: +55 (31) 3201-1799

# Build settings
markdown: rdiscount
theme: minima
plugins:
  - jekyll-feed
  - jekyll-assets

minima:
  date_format: "%d/%m/%Y"

assets:
  liquid: false
  prefix: "/assets"
  integrity: false
  autowrite: true
  digest: false
  strict: false
  caching:
    enabled: true
    path: ".jekyll-cache/assets"
    type: file
  precompile: []
  cdn:
    baseurl: false
    prefix: false
  plugins:
    img:
      optim: {}
    compression:
      js:
        enabled: true
        opts: {}
      css:
        enabled: true
  sources:
  - assets/css
  - assets/fonts
  - assets/images
  - assets/javascript
  - assets/image
  - assets/img
  - assets/js

  - _assets/css
  - _assets/fonts
  - _assets/images
  - _assets/javascript
  - _assets/image
  - _assets/img
  - _assets/js

  - _sass

  - css
  - fonts
  - images
  - javascript
  - image
  - img
  - js

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
